#! /usr/bin/env bash
#
# raspi-debian - a set of scripts to configure Debian on Raspberry Pi 4
# and prepare it for application development with PostgreSQL and RabbitMQ
#
# DESCRIPTION:
# Installs docker and docker-compose.

set -e

script=${0##*/}
exec &> >(tee "$script.log")

print () {
    printf "\n\033[1m[$script] $1\033[0m\n"
}

print 'Installing Docker'
curl -fsSL https://get.docker.com -o get-docker.sh
sh ./get-docker.sh

print 'Installing docker-compose'
apt-get install docker-compose -y

print "Script completed successfully."
exit 0;

# vim: ft=sh:sw=4:et:ai

